version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rocket_panel_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /proc:/host/proc:ro  # For system stats
    environment:
      - DATABASE_URI=sqlite:///./sql_app.db
      - SECRET_KEY=${SECRET_KEY}

  frontend:
    image: node:20-alpine
    container_name: rocket_panel_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"  # Vite default port
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

#  nginx:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./infrastructure/nginx:/etc/nginx/conf.d
#    depends_on:
#      - backend
#      - frontend
